language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: firebase
  token:
    secure: "NuZ4cvlN9acpL1LegG74bjQZGa6o7LeLjJ+iZfOTPy1LKdOHfCZZOFjLXOKitb05nDoqdPkYXBpqlDX/pBlBnTv3I4Hy0lFMCaJ9to/usASFBDQUoyFl6r8y0km4erQPzM5fWBvg0Zu5gARqrngIwdYdeaXxQBcU/IMVN+WnmIZyCK0hEaT7jMJfpKreyHkCnSaMaxFhMXjgdsg9QU4tJI5211dqcXICysLeANhF34inft+2vFCcshjpC44f52yt3MhoCD2NQgdrQDuTj4b9TcUhJpcLltOqCQnvfzFjuRss4+NwOwbtmJVlL1RhITTF6lGDuLwSQMO0KEQ6lp/1N20+m8F/Vs+rxOwkzlf9ot1IBwgJGX5K20jFa9p1oF9L0uwNbbg9K/LUP2+oLM9DPlvsMgTHE0makdsbsIMvprQLUExI+7Q/06Op7+ZbsXM3EzZB83mQ2SgXMSAcmWlkl6a4YDNu6pBxCh4k1Gk23o71JBrwecvW1R0whjkdj8CWbDmkD0ggUwFqjL/I8v7WezYyEkUl0dC/p/CxrcNbvNr8zXZwfunuNtk4KJWZR67wHvTiHP1srowJQZeXFNLTGYlDLQdBWJ6n/Q9gaTI6ecTe4B9eZvGfDjeeIO3D8sEJ38AWH7hXFJcQO/CHUDyZehrPfWBLDW2mue3hL6pWYLU="
  project: "learnReact"
